# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='conteng',
            new_name='content',
        ),
    ]
